### PR TITLE
Remove upstart support

### PR DESCRIPTION
**Pull request by BryanQuigley**
Removes upstart conf file and notes about using it

### CODE REVIEW

**Comment by spandruvada** [comment]
There are some old ubuntu distribution still using upstart. So I will leave upstart support for some more time.

**Comment by BryanQuigley** [comment]
@spandruvada No need (at least that I understand) from the Ubuntu project, we generally don't do full backports of upstream for older releases. 

14.04 is the only mainstream supported release not using systemd -it will almost certainly not be updated to a trunk release.  I've been proposing removals for a couple Ubuntu specific projects and they've found it fine to remove.

**Comment by spandruvada** [comment]
On Sun, 2017-12-10 at 13:37 +0000, BryanQuigley wrote:
> @spandruvada No need (at least that I understand) from the Ubuntu
> project, we generally don't do full backports of upstream for older
> releases.
> 14.04 is the only mainstream supported release not using systemd -it
> will almost certainly not be updated to a trunk release. I've been
> proposing removals for a couple Ubuntu specific projects and they've
> found it fine to remove.
I need Colin, King's input who maintains thermald in Ubuntu.
I will be fine if he doesn't need this support anymore.

Thanks,
Srinivas

**Comment by BryanQuigley** [comment]
@ColinIanKing - still need upstart support?  Thanks!

**Comment by ColinIanKing** [comment]
upstart support can be removed now, thanks!

**Comment by spandruvada** [comment]
On Sun, 2017-12-10 at 15:01 -0800, Colin Ian King wrote:
> upstart support can be removed now, thanks!
Then I will apply changes from Marko.

Thanks,
Srinivas

**Comment by spandruvada** [comment]
Applied

**Pull request merged**
