### PR TITLE
Honor ACPI _CRT for processor thermal zone

### PR DESCRIPTION
**Pull request by khfeng**
There are some new fanless platforms use DPTF's virtual sensor instead
of INT340X devices.

Because of that, the _PSV is no longer in use, at least not directly,
hence its value may set higher then _CRT. To a fanless system that means
no cooling device gets activated before _CRT, so the system will be
considered overheated by Linux kernel, and gets shutdown by the kernel.

To avoid that, we use 85% of _CRT value as our new _PSV value.
A 15% margin below _CRT should be enough for passive cooling devices to
clamp the temperature down.

This is a compromise, but we need this until we have full DPTF support.

### CODE REVIEW

**Comment by spandruvada** [comment]
Could you send me the acpidump of this system?
#acpidump > acpi.out
and also
#cat /sys/bus/acpi/devices/INT3400:00/physical_node/uuids/available_uuids

**Comment by khfeng** [comment]
[dump.zip](https://github.com/intel/thermal_daemon/files/2593915/dump.zip)

**Comment by khfeng** [comment]
available_uuids:
3A95C389-E4B8-4629-A526-C52C88626BAE
97C68AE7-15FA-499c-B8C9-5DA81D606E0A

**Comment by khfeng** [comment]
> There is no hard and fast rule that the first trip point has to be critical by the spec for acpitz zone.
> So you have to check type CRITICAL for using as the critical temp.

Will do.

> The acpi critical can be garbage too. So I will check for non zero.

Will do.

> "new_passive = acpitz_crit->get_trip_temp() / 1000 * 85 / 100 * 1000;"
> Why not simply
> acpitz_crit->get_trip_temp() 85 / 100;?

Because temperature uses 1000 as its basic unit.
But it doesn't affect much if we ignore it. Will do.

> 
> The 15% is too aggressive. We had this in CPU thermal zone before and users complaints about performance issues. I will suggest some 10C from critical which is done in CPU thermal zone when processor_thermal is absent.

Ok, I'll see if 10C is enough on the platform in question.

**Comment by khfeng** [comment]
Looks like 10C margin is not enough. What to do next?
Though I still patched the processor_thermal's passive trip point value because it's not absent.

**Comment by spandruvada** [comment]
On Thu, 2018-11-22 at 19:01 -0800, Kai-Heng Feng wrote:
> Looks like 10C margin is not enough. What to do next?
> Though I still patched the processor_thermal's passive trip point
> value because it's not absent.

Does running thermald with --poll-interval=1

helps with 10C margin?


Thanks,
Srinivas

**Comment by khfeng** [comment]
No, the system still shutdowns with 10C margin and --poll-interval=1

**Comment by spandruvada** [comment]
You said that there is no passive trip for this device. So we can add the new 15C offset passive trip only when there is passive trip configured by the system.
In this way the change will only impact such platforms.
________________________________________

**Comment by khfeng** [comment]
Not really, the passive trip does exist, but the value is higher than _CRT so the system shutdown by ACPI subsystem before the hitting the passive trip.

**Comment by spandruvada** [comment]
On Fri, 2018-11-30 at 08:34 -0800, Kai-Heng Feng wrote:
> Not really, the passive trip does exist, but the value is higher than
> _CRT so the system shutdown by ACPI subsystem before the hitting the
> passive trip.
So this can be the condition to add a new trip. So when configured
passive trip is  equal or more than critical or too close with in 5C,
add this new passive trip at offset "critical - 15C".

**Comment by khfeng** [comment]
@spandruvada I force pushed a new version, please review it, thanks!

**Comment by khfeng** [comment]
Another gentle ping...

**Comment by spandruvada** [comment]
You need something like this as the temp is in 1000s.

git diff
diff --git a/src/thd_engine_default.cpp b/src/thd_engine_default.cpp
index c9869c7..9c806c3 100644
--- a/src/thd_engine_default.cpp
+++ b/src/thd_engine_default.cpp
@@ -286,7 +286,7 @@ bool cthd_engine_default::add_int340x_processor_dev(void)
                                        }
                                }
 
-                               if (critical && passive + 5 >= critical) {
+                               if (critical && passive + 5000 >= critical) {
                                        new_passive = critical - 15 * 1000;
                                        if (new_passive < critical)
                                                trip->thd_trip_update_set_point(new_passive);

**Comment by khfeng** [comment]
Sorry for missing that one.
I just force-pushed a new version.

Thanks for the review.

**Comment by spandruvada** [comment]
Pulled. s

Thanks,
Srinivas

**Pull request merged**
