### PR TITLE
K10temp

### PR DESCRIPTION
**Pull request by khfeng**

### CODE REVIEW

**Comment by spandruvada** [comment]
You can't ignore cpuid check by default. This was added to remove regression.
Same Ubuntu can work server platforms, but thermald can't run on server platforms as it doesn't have multi socket support. Also the power limits were not set correctly on some server platforms as there was no users of those limits.
Also I have no way to verify AMD platforms to see if it caused any regression. So I have to blindly take the change.

**Comment by khfeng** [comment]
So instead of ignoring CPUID, we should check for non-server CPUs in check_cpu_id()?

**Comment by cooper151288** [comment]
Is there a reason we whitelist supported models rather than blacklisting multiprocessing/multisocket capable chips?
There is good control of AMD fam15h CPUs available in PCI config space, some of which works on locked chips too:
D18F4 0x10c bits 11:0 is the node TDP limit- this only works on unlocked. fam15h_power driver doesn't update the cap into power1_crit, unfortunately.
D18F4 0x110, 11:0 adjusts a timer which, if increased, increases the reported power consumption. If set to 0 it allows uncapped boosting. This works on locked processors as well as locked. Bit 12 of this reg, while undocumented seems to act as a divisor on this timer. This also works on locked units.

**Comment by cooper151288** [comment]
AMD CPUs (fam15h) also have the capability for adding a slew rate to the temperature reported by k10temp. This may be useful to filter out spikes that can happen when boosting (especially when the boosted states are overclocked). To enable, set bit 23 of D18F3 0x64.
The slew rate is configurable via D18F3 0xa4.

**Comment by spandruvada** [comment]
On Wed, 2019-04-03 at 23:05 -0700, Kai-Heng Feng wrote:
> So instead of ignoring CPUID, we should check for non-server CPUs in
> check_cpu_id()?
The problem is that someone may be using 10 years old server. If you
miss any id then this will be a problem.
Thanks,Srinivas

**Comment by spandruvada** [comment]
On Thu, 2019-04-04 at 00:22 -0700, Matt Cooper wrote:
> AMD CPUs (fam15h) also have the capability for adding a slew rate to
> the temperature reported by k10temp. This may be useful to filter out
> spikes that can happen when boosting (especially when the boosted
> states are overclocked). To enable, set bit 23 of D18F3 0x64.
> 
> The slew rate is configurable via D18F3 0xa4.
In this case it is better to add a K10 sensor class by itself with all
goodies.
Thanks,Srinivas

**Comment by cooper151288** [comment]
There should be plenty of transferrable code to make this work from programs like turionpowercontrol/amdmsrtweaker/k15ctl.
I've been meaning to lump them all together into a processor configuration tool with an interface for a while now. I'll want to implement things that shouldn't be in thermald (ie lowering thermal/power safeguards)
Did the old intel MSR RAPL work by setting a TDP limit register? If so that could be reused to work on unlocked fam15h CPUs where APM master mode is enabled. There is a way to get interrupts sent for TDP stuff, and maybe for temperatures too but I don't think the kernel understands it.

**Comment by spandruvada** [comment]
No activity for long. Require support from the vendor.

**Comment by khfeng** [comment]
Sorry, I didn't have time to work on this.

I'll update this pull request, it's till on my todo list.

**Pull request closed without merging**
