### PR TITLE
Porting adative policy support for Android

### PR DESCRIPTION
**Pull request by songhowl2**
Following items are done for Android:
   Porting lzma functions from intel dptf project
   Remove UpClient
   Remove libevdev-devel related code in android
   Add adaptive related handle in android_main.c
   Fix android.mk

### CODE REVIEW

**Comment by songhowl2** [comment]
It porting the adaptive policy for android

**Comment by spandruvada** [comment]
Are these newly included files released under GPL v2 or later?

**Comment by songhowl2** [comment]
Hi
Since the add files
                                src/thd_lzma_dec.cpp \
                                src/LzmaDec.c
is from https://github.com/intel/dptf
And I have checked the LICENSE.txt<https://github.com/intel/dptf/blob/master/LICENSE.txt>.
It  says that.
"The contents of this repository is licenced under the Apache 2.0 license for
user mode components and a dual BSD/GPLv2 license for the kernel mode
components."

Best regards
Bill

**Comment by spandruvada** [comment]
Applied. Thanks.

**Pull request closed without merging**
