### PR TITLE
Add initial support for DPTF adaptive performance policy

### PR DESCRIPTION
**Pull request by mjg59**
This is a very rough attempt at implementing support for the adaptive performance DPTF policy. I have no documentation on this, so it's a best guess in many places. It only supports a subset of the conditions and actions and I'm really not sure that the hack that uses the dram RAPL engine if the sensor is called TMEM is correct, so please be as critical as necessary.

### CODE REVIEW

**Comment by spandruvada** [comment]
Thanks you Matthews for pulll requests.
As a open source developer at OTC, I don't have access to DPTF specifications. So I can't really look at Adaptive performance changes . I can take other changes slowly.

Please keep updates to your tree and let other testers tests on other platforms also. Once I have enough information on adaptive policy, I will apply.

**Comment by spandruvada** [comment]
So there is a dependency on kernel patches, which you submitted. So need to bring in those patches first.

**Comment by spandruvada** [comment]
Pushed all these patches to mg_patches_test branch. If anyone wants to Beta tests.

**Comment by bhack** [comment]
@mj59 Thanks for you effort. What do you think about this [Lenovo statement](https://www.phoronix.com/scan.php?page=news_item&px=Lenovo-Linux-Thermal-Throttling). It Is not clear to me the how that firmware will interact with this.

**Comment by mrhpearson** [comment]
Hi,
I was looking @mjg59 blog the other day about this change. First off (with my Lenovo hat off) - very cool and kudos. I wonder if this will encourage Intel to release some details publicly?

Lenovo hat back on - I don't really know how this will interact with our new firmware. I assume if you're not using thermald then it doesn't really matter, but otherwise the two pieces will potentially be fighting one another. I was planning to try it out on one of our devices to see what happens but haven't had time this week. 
All our 2020 (linux supported) platforms will have the thermal firmware and we have a few older platforms that should be getting updated next month (fingers crossed...), I don't *think* this change is really needed for our platforms that have the updated thermal firmware - it is already taking care of the different conditions and has been tuned for optimal performance in the factory. I am sure there will be people in the community who want to tweak the behaviour and that will be trickier - we have safety regulations we have to meet and when I've asked previously about adding the ability to just disable any power throttling the response was a firm no. We have some improvements coming soon - I'm just waiting on permission to disclose publicly...

I did forward the details about @mjg59 work being done to the firmware team last week to get their feedback but they didn't really have anything to add. If there is anything specific that I should ask them please let me know.

Sorry - in all that rambling nothing very useful. If you are looking for specifics let me know and I'll do the best to find answers. Thanks for adding me to the thread.

**Comment by bhack** [comment]
Thank for your feedback. Yes It would be really nice to know if the new firmware will conflict with Thermald with or without this patch and so if Is It the case to uninstall Thermald in each case or just if this will not merged on that Lenovo devices.

I.e. the other workarund solution conflicted with Thermald: https://github.com/erpalma/throttled/blob/master/README.md#thermald

/cc @erpalma

**Comment by mrhpearson** [comment]
I played with this some and I think I need some guidance on what needs testing and if what I'm doing makes sense. I appreciate I really need to read the code but it's been a crazy week and I wanted to get some results back so haven't done that. 

I built and ran this version of thermald. I needed to generate a thermal-conf.xml so used dptfxtract for that - it was interesting how it generated 5 different config files and I really need to understand what it is doing as I suspect that is important (let me know if you want them posted somewhere to review) . I've not personally had much to do with thermald so if there are pointers on what is better please let me know. 

I'm running the latest version of our firmware and it has a feature where you can switch between thermal modes (low, normal, high - with corresponding power settings of 7.5W for low, 14.5 for normal and 51W for high).

With this thermald running I seem to be limited to 15W (and around 75C). I'm running Intels Thermal Analysis Tool and the Package power was clamped at 15 (running a kernel build to keep things busy).

If I'm not running thermald but just Lenovo firmware then in performance mode the power goes up to 51W and Temperature to 92 - so better performance (as long as it's in desk mode - you won't get that when it's in lap mode). So...in the 'battle' to control the power thermald is winning, but in this case it's not giving the optimal performance. I suspect that's related to the config files I've generated. 

I tested lap mode. In this case our firmware detects it's on a lap and lowers the power to 14.5W (or 7.5W if you have low mode selected). If I'm running thermald I get 10W (it was a bit quirky - I saw 15W at one point...but only briefly).

Hope the above is helpful - happier to collect more details or try anything out if it would be useful. Especially if I'm not doing things right :)

I'm going to try it on some platforms which don't have the updated firmware - I know we have plenty of unhappy customers because we haven't been able to backport it everywhere and I'm really hoping this is a good solution there (longer term I also suspect we'll all be better off if we can support DPTF properly)

Let me know if any questions.
Thanks
Mark

**Comment by mjg59** [comment]
@mrhpearson You need to run with the --adaptive option, which should then avoid the need to use dptfxtract and any xml config files. If you don't do that it's equivalent to the current upstream.

**Comment by mjg59** [comment]
(But also it would be super helpful to know how Lenovo firmware differentiates between Linux and a DPTF-enabled operating system, and what the differences in behaviour are)

**Comment by mrhpearson** [comment]
@mjg59 If I run with --adaptive I get:
[1588176598][ERR]Unable to open GDDV data vault
I ran with loglevel=debug but I didn't see anything obvious jump out - any ideas what I'm missing?

I'll check with the firmware team how they determine the difference - afraid you'll have to wait a while for the reply as they're in Japan and its a holiday there this week.

**Comment by mjg59** [comment]
@mrhpearson Did you build a kernel with the additional patches in the repo? They're not upstream yet.

**Comment by mrhpearson** [comment]
Crud...missed those. Sorry!

**Comment by spandruvada** [comment]
Send me your thermal-conf.xml. You need to at least have 5.4 kernel (For ICL). Also cat /sys/bus/pci/devices/0000:00:04:.0/power_limits/*.
For Lenovo systems also #rdmsr 0x1a2

Thanks,
Srinivas

**Comment by mrhpearson** [comment]
So some interesting results but not sure they will be what you are looking for. Thanks for the pointer on the patches - I hadn't seen the instructions on your fork and I think I'm now setup correctly.
Running patched 5.7.0-rc3 on a X1Carbon7 (WhiskeyLake CPU). Doing a kernel build with multiple threads to keep it busy

I confirmed with the Lenovo firmware that it was in deskmode with high performance mode enabled (power up to 51W) and then ran thermald --adaptive. At this point the power fluctuated between 10 and 15W - going up and down in small increments (MSR PL1 changing value). Temperature stayed steady around 65 to 70C.

I then picked up the laptop to get it in lap mode (I'm assuming the DPTF tables should handle this as that's their raison d'etre) and interestingly the power then fixed solidly at 15W (temp at 70C). 
I waited for it to drop back into deskmode - but it didn't - so for the X1C7 at least that seems broken.

As a minor note - stopping thermald doesn't return everything to 'normal' operation. A reboot is needed at that point (I'm assuming registers different to what our FW uses have been tweaked). 

Srinivas - I'll forward you my xml file shortly. The other details are:
/sys/bus/pci/devices/0000:00:04.0/power_limits/power_limit_1_tmax_us 0
/sys/bus/pci/devices/0000:00:04.0/power_limits/power_limit_0_tmin_us 28000000
/sys/bus/pci/devices/0000:00:04.0/power_limits/power_limit_0_min_uw 125000
/sys/bus/pci/devices/0000:00:04.0/power_limits/power_limit_1_min_uw 51000000
/sys/bus/pci/devices/0000:00:04.0/power_limits/power_limit_1_step_uw 500000
/sys/bus/pci/devices/0000:00:04.0/power_limits/power_limit_0_tmax_us 32000000
/sys/bus/pci/devices/0000:00:04.0/power_limits/power_limit_0_max_uw 51000000
/sys/bus/pci/devices/0000:00:04.0/power_limits/power_limit_1_max_uw 51000000
/sys/bus/pci/devices/0000:00:04.0/power_limits/power_limit_1_tmin_us 0
/sys/bus/pci/devices/0000:00:04.0/power_limits/power_limit_0_step_uw 500000
# rdmsr 0x1a2
364000

**Comment by mjg59** [comment]
@mrhpearson Ok, thanks - I should have an X1v7 showing up in the next few weeks and I'll dig into it. Are you able to open an issue in the github.com/mjg59/thermal_daemon repository and attach the output of the acpidump command when run as root?

**Comment by mrhpearson** [comment]
No problem - done.

**Comment by spandruvada** [comment]
As an open source developer I don't have access to the DPTF/DTT specifications. I will bring in these changes to main line in the next release. It may be modified from what is submitted with due credit given to the author. We need volunteers to test implement workaround if this causes any negative user experience. So initially it will still have some command line option to turn on this feature.
Anyway this require the kernel patches merged in, which I will  test first to see if we can  catch 5.8.

**Comment by bhack** [comment]
I hoped that some DPTF team member for Chrome OS could comment here but....

**Comment by superm1** [comment]
Afaict Chromeos only supports passive policies today. so I'm not sure how much their comments help this discussion.

**Comment by bhack** [comment]
Probably not so much if they don't have access to the dynamic specs. 
But we don't know this. It could be just that they are under NDA on the dynamic part or that the dynamic part Is in the roadmap. Who knows...

**Comment by bhack** [comment]
@spandruvada Let us know when you will try to submit the kenel patches.

**Comment by bhack** [comment]
What is the STOA?

**Comment by spandruvada** [comment]
kernel patches are merged to 5.8-rc1. So someone can try on top of 5.8-rc1.

**Comment by estan** [comment]
Great initiative @mjg59.

I tried this out on my Lenovo Thinkpad X1 Carbon 6th (20KH007BMX), running Ubuntu 20.04 with mainline 5.8rc2 kernel, with laptop on desk and plugged into standard 65 W charger, running `thermald --no-daemon --adaptive` and starting `stress -c 8`:

bild

Looks like it's still being throttled down to 75-80° C / 15 W under load.

Ambient temperature was 29° C (hot in Sweden today and no AC :p).

This is similar to the behavior I see with default Ubuntu 20.04 kernel (5.4.0-39.43) and thermald 1.9.1-1ubuntu0.1 package.

Let me know if you want me to dump some tables out or something that would help.

**Comment by spandruvada** [comment]
On Sat, 2020-06-27 at 11:35 -0700, Elvis Stansvik wrote:

Great initiative @mjg59<https://github.com/mjg59>.

I tried this out on my Lenovo Thinkpad X1 Carbon 6th (20KH007BMX), running Ubuntu 20.04 with mainline 5.8rc2 kernel, with laptop on desk and plugged into standard 65 W charger, running thermald --no-daemon --adaptive and starting stress -c 8:

[bild]<https://user-images.githubusercontent.com/86675/85929359-5fda7d80-b8b4-11ea-9e94-a78c1b817d5c.png>

Please attach output of acpidump.

Thanks.


Looks like it's still being throttled down to 75-80° C / 15 W under load.

Ambient temperature was 29° C (hot in Sweden today and no AC :p).

This is similar to the behavior I see with default Ubuntu 20.04 kernel (5.4.0-39.43) and thermald 1.9.1-1ubuntu0.1 package.

Let me know if you want me to dump some tables out or something that would help.

**Comment by spandruvada** [comment]
On Sat, 2020-06-27 at 11:35 -0700, Elvis Stansvik wrote:

Great initiative @mjg59<https://github.com/mjg59>.

I tried this out on my Lenovo Thinkpad X1 Carbon 6th (20KH007BMX), running Ubuntu 20.04 with mainline 5.8rc2 kernel, with laptop on desk and plugged into standard 65 W charger, running thermald --no-daemon --adaptive and starting stress -c 8:

[bild]<https://user-images.githubusercontent.com/86675/85929359-5fda7d80-b8b4-11ea-9e94-a78c1b817d5c.png>

Looks like it's still being throttled down to 75-80° C / 15 W under load.

Ambient temperature was 29° C (hot in Sweden today and no AC :p).

This is similar to the behavior I see with default Ubuntu 20.04 kernel (5.4.0-39.43) and thermald 1.9.1-1ubuntu0.1 package.

Let me know if you want me to dump some tables out or something that would help.

**Comment by estan** [comment]
> Please attach output of acpidump.
> 
> Thanks

@spandruvada I moved this over to an issue on @mjg59's fork here: https://github.com/mjg59/thermal_daemon/issues/7. It has an acpidump attached.

**Comment by spandruvada** [comment]
I merged all changes to v2.3_development branch with minor change for removing my name from authorship. I have to use manual merge for conflicts. I hope merged correctly. I did a diff with mjg59/thermal_daemon to check.

**Pull request closed without merging**
