### PR TITLE
thd_cdev*: fix cpufreq and handle the case when (max_state==min_state)

### LINKED ISSUE #226: cpufreq cooling device: unexpected and erratic behaviour
**To reproduce:**
Using the config below as config.xml, issue the command:
`# thermald --no-daemon --ignore-default-control  --config-file=config.xml --loglevel=info`

**Result:**
The log shows that the cooling device "cpufreq" is set to an increasingly lower state despite that the target temperature has never been reached:
```
[1589648691][INFO]>>thd_cdev_set_state temperature 70000:45000 index:6 state:0 :zone:10 trip_id:0 target_state_valid:0 target_value :0 force:0
[1589648691][INFO]op->device:cpufreq -5
[1589648691][INFO]Set : threshold:70000, temperature:45000, cdev:6(cpufreq), curr_state:-5, max_state:11
[1589648695][INFO]>>thd_cdev_set_state temperature 70000:45000 index:6 state:0 :zone:10 trip_id:0 target_state_valid:0 target_value :0 force:0
[1589648695][INFO]op->device:cpufreq -6
[1589648695][INFO]Set : threshold:70000, temperature:45000, cdev:6(cpufreq), curr_state:-6, max_state:11
[1589648699][INFO]>>thd_cdev_set_state temperature 70000:45000 index:6 state:0 :zone:10 trip_id:0 target_state_valid:0 target_value :0 force:0
[1589648699][INFO]op->device:cpufreq -7
[1589648699][INFO]Set : threshold:70000, temperature:45000, cdev:6(cpufreq), curr_state:-7, max_state:11
[1589648703][INFO]>>thd_cdev_set_state temperature 70000:45000 index:6 state:0 :zone:10 trip_id:0 target_state_valid:0 target_value :0 force:0
[1589648703][INFO]op->device:cpufreq -8
```
Using `strace` clearly shows that it is writing garbage to `sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq` and some writes fail with EINVAL:
```
[pid 17702] 15:52:21 write(8</sys/devices/system/cpu/cpufreq/policy2/scaling_max_freq>, "-350469331", 10) = -1 EINVAL (Invalid argument)
```

**Used configuration:**
```xml
<?xml version="1.0"?>
<ThermalConfiguration>
  <Platform>
    <Name>Example Laptop</Name>
    <ProductName>*</ProductName>
    <Preference>QUIET</Preference>
    <ThermalSensors>
      <ThermalSensor>
        <Type>cpu-temp</Type>
        <Path>/sys/class/thermal/thermal_zone7/temp</Path>
      </ThermalSensor>
    </ThermalSensors>
    <ThermalZones>
      <ThermalZone>
        <Type>cpu</Type>
        <TripPoints>
          <TripPoint>
            <SensorType>cpu-temp</SensorType>
            <Temperature>70000</Temperature>
            <type>passive</type>
            <ControlType>SEQUENTIAL</ControlType>
            <CoolingDevice>
              <index>1</index>
              <type>cpufreq</type>
              <influence>100</influence>
              <SamplingPeriod>1</SamplingPeriod>
            </CoolingDevice>
          </TripPoint>
        </TripPoints>
      </ThermalZone>
    </ThermalZones>
  </Platform>
</ThermalConfiguration>
```

### PR DESCRIPTION
**Pull request by aliemjay**
This should fix #226.

Please see the commit messages for description.

### CODE REVIEW

**Comment by aliemjay** [comment]
Yes, this  fixed it. 

Though an edge case, the problem is still true for any cooling device with `max_state==min_state`. This can be easily shown for cpufreq by setting the maximum frequency to the lowest possible before starting `thermald`. However, I should have fixed it in a separate PR.

Please feel free to close this.
Thank you.

**Comment by spandruvada** [comment]
That is the setting before thermald started, so that much be respected.

**Comment by aliemjay** [comment]
Sorry, I think I should've put it more clearly that the problem in the linked issue is really two:

1. `thd_cdev_cpufreq::max_state` is not initialized, which was solved by your commit.

2. When `max_state==0` and `min_state==0`, as is the case here, the default exponential controller calls `set_curr_state()` with ANY integer value (even negative) causing out-of-bounds access to `::cpufreqs[]` and, then, writing random invalid values to `sysfs`. This was due to incomplete logic in `thd_clamp_state_*()`, which I tried to address this in the first commit in this PR.

**Comment by spandruvada** [comment]
This is not urgent fix. So I will include as part of my development branch for next major release.
Your current issue you reported by the fix.

**Pull request closed without merging**
