### PR TITLE
tests: Add some experimental umockdev tests

### PR DESCRIPTION
**Pull request by benzea**
Maybe we can at least regession tests e.g. parsing of the adaptive
tables this way.

Note:
 * This needs umockdev changes, see https://github.com/martinpitt/umockdev/pull/191#pullrequestreview-1039056594
 * I just dumped it into the tests directory, not sure what do to with it
 * No idea how useful, but if we get more HW configs from different machines, we might at least have a small chance of doing regression tests
 * To be useful, we should probably analyse more stuff, like whether thermal control actually works ... or at least of certain configurations are done properly on specific machines (maybe saving the before/after startup sysfs state from a reference run and comparing that?)

Anyway, dumping it here. Unfortunately, I am unlikely to spend much more time on it in the future. But I figured I should at least post it.

Marking as draft as the umockdev changes are not ready.

### CODE REVIEW

**Comment by spandruvada** [comment]
I appreciate this effort. Since there are so many combinations of configurations, it is great to have a regression test suit. I have 10+ systems, when I release I just do some tests on them but that is not enough.

**Comment by benzea** [comment]
If you have an idea of what/how one can test thermald a bit, I might be able to assist a bit to actually get things up and running. So far, it is largely boilerplate stuff, but I guess one could e.g. make a recording of sysfs temperature changes and the expected behaviour.

Note that I was considering using UMLs `time-travel` mode with infinite CPU to avoid timing issues. That way one could easily feed sysfs temperature sensor changes and check whether thermald reacts correctly without being as susceptible to timing differences between runs.

**Comment by benzea** [comment]
> Note that I was considering using UMLs `time-travel` mode with infinite CPU to avoid timing issues.

Though, to be fair, with the 4 second polling model, it should also work quite well to just wait for the mainloop iteration by reading stdout/stderr and doing sysfs changes just after the mainloop ran.

**Comment by spandruvada** [comment]
Did you make in progress here?

**Comment by spandruvada** [comment]
I will close the pull request as this is open for a while with no progress. I am adding tests as a script in the next rev,

**Pull request closed without merging**
